// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
///


class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAck8p1K5LHlPWYsXTvb5nlVJJZJvopSuY',
    appId: '1:568950822747:web:8477e0c1bf91e17217ac7e',
    messagingSenderId: '568950822747',
    projectId: 'boongboong-into-the-room',
    authDomain: 'boongboong-into-the-room.firebaseapp.com',
    storageBucket: 'boongboong-into-the-room.appspot.com',
    measurementId: 'G-00V8QLHS1P',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBFrZ405T7PxP-cj5b0_U3k6tu6pz2NUgk',
    appId: '1:568950822747:android:b64870ef188e045a17ac7e',
    messagingSenderId: '568950822747',
    projectId: 'boongboong-into-the-room',
    storageBucket: 'boongboong-into-the-room.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyB4bv-gIWQbbD8AVjdreXF9SsBS5bQ7sjE',
    appId: '1:568950822747:ios:6bf34ef52ff4fa0717ac7e',
    messagingSenderId: '568950822747',
    projectId: 'boongboong-into-the-room',
    storageBucket: 'boongboong-into-the-room.appspot.com',
    iosClientId: '568950822747-1v8av5vuv722oi59so87j896849h082u.apps.googleusercontent.com',
    iosBundleId: 'com.into.the.room.boongboongIntoTheRoom',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyB4bv-gIWQbbD8AVjdreXF9SsBS5bQ7sjE',
    appId: '1:568950822747:ios:6bf34ef52ff4fa0717ac7e',
    messagingSenderId: '568950822747',
    projectId: 'boongboong-into-the-room',
    storageBucket: 'boongboong-into-the-room.appspot.com',
    iosClientId: '568950822747-1v8av5vuv722oi59so87j896849h082u.apps.googleusercontent.com',
    iosBundleId: 'com.into.the.room.boongboongIntoTheRoom',
  );
}
